const fakeItems = [
    {
        id: '1',
        name: 'Item 1',
        created: '2021-09-01',
        description: 'Description 1',
        modified: '2021-09-01',
        fake: '100',
        trush: '100',
        kudos: '100',
        disappointed: '100',
        is_rate: true,
        is_mark: true,
        image: [
            {
                id: '1',
                url: 'https://picsum.photos/200/300',
            },
            {
                id: '2',
                url: 'https://picsum.photos/200/300',
            },
        ],
        video: [],
        author: {
            id: '1',
            name: 'Author 1',
            avatar: 'https://picsum.photos/200/300',
            coins: '100',
            listing: 'Post A, Post B, Post C',
        },
        category: {
            id: '1',
            name: 'Category 1',
            has_name: true,
        },
        state: 'published',
        is_blocked: false,
        can_edit: true,
        banned: false,
        can_mark: true,
        can_rate: true,
        url: 'https://picsum.photos/200/300',
        message: 'Message 1',
    },
    {
        id: '5',
        name: 'Item 1',
        created: '2021-09-01',
        description: 'Description 1',
        modified: '2021-09-01',
        fake: '100',
        trush: '100',
        kudos: '100',
        disappointed: '100',
        is_rate: true,
        is_mark: true,
        image: [
            {
                id: '1',
                url: 'https://picsum.photos/200/300',
            },
            {
                id: '2',
                url: 'https://picsum.photos/200/300',
            },
        ],
        video: [],
        author: {
            id: '1',
            name: 'Author 1',
            avatar: 'https://picsum.photos/200/300',
            coins: '100',
            listing: 'Post A, Post B, Post C',
        },
        category: {
            id: '1',
            name: 'Category 1',
            has_name: true,
        },
        state: 'published',
        is_blocked: false,
        can_edit: true,
        banned: false,
        can_mark: true,
        can_rate: true,
        url: 'https://picsum.photos/200/300',
        message: 'Message 1',
    },
    {
        id: '4',
        name: 'Item 1',
        created: '2021-09-01',
        description: 'Description 1',
        modified: '2021-09-01',
        fake: '100',
        trush: '100',
        kudos: '100',
        disappointed: '100',
        is_rate: true,
        is_mark: true,
        image: [
            {
                id: '1',
                url: 'https://picsum.photos/200/300',
            },
            {
                id: '2',
                url: 'https://picsum.photos/200/300',
            },
        ],
        video: [],
        author: {
            id: '1',
            name: 'Author 1',
            avatar: 'https://picsum.photos/200/300',
            coins: '100',
            listing: 'Post A, Post B, Post C',
        },
        category: {
            id: '1',
            name: 'Category 1',
            has_name: true,
        },
        state: 'published',
        is_blocked: false,
        can_edit: true,
        banned: false,
        can_mark: true,
        can_rate: true,
        url: 'https://picsum.photos/200/300',
        message: 'Message 1',
    },
    {
        id: '2',
        name: 'Item 1',
        created: '2021-09-01',
        description: 'Description 1',
        modified: '2021-09-01',
        fake: '100',
        trush: '100',
        kudos: '100',
        disappointed: '100',
        is_rate: true,
        is_mark: true,
        image: [
            {
                id: '1',
                url: 'https://picsum.photos/200/300',
            },
            {
                id: '2',
                url: 'https://picsum.photos/200/300',
            },
        ],
        video: [],
        author: {
            id: '1',
            name: 'Author 1',
            avatar: 'https://picsum.photos/200/300',
            coins: '100',
            listing: 'Post A, Post B, Post C',
        },
        category: {
            id: '1',
            name: 'Category 1',
            has_name: true,
        },
        state: 'published',
        is_blocked: false,
        can_edit: true,
        banned: false,
        can_mark: true,
        can_rate: true,
        url: 'https://picsum.photos/200/300',
        message: 'Message 1',
    },
    {
        id: '3',
        name: 'Item 1',
        created: '2021-09-01',
        description: 'Description 1',
        modified: '2021-09-01',
        fake: '100',
        trush: '100',
        kudos: '100',
        disappointed: '100',
        is_rate: true,
        is_mark: true,
        image: [
            {
                id: '1',
                url: 'https://picsum.photos/200/300',
            },
            {
                id: '2',
                url: 'https://picsum.photos/200/300',
            },
        ],
        video: [],
        author: {
            id: '1',
            name: 'Author 1',
            avatar: 'https://picsum.photos/200/300',
            coins: '100',
            listing: 'Post A, Post B, Post C',
        },
        category: {
            id: '1',
            name: 'Category 1',
            has_name: true,
        },
        state: 'published',
        is_blocked: false,
        can_edit: true,
        banned: false,
        can_mark: true,
        can_rate: true,
        url: 'https://picsum.photos/200/300',
        message: 'Message 1',
    },
];

export default fakeItems;
